imports: ./imports
exports: ./exports
imagetype: png
unicodestart: 0x000021
unicodeend: 0x00007E
captions: true
additionalprompts:
  - unicode
  - font
  - rune
  - letter
  - figure
  - glyphs
  - character
  - symbol
  - black
  - transparent
  - center
