name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: true

      - name: Download modules
        run: go mod download

      - name: Format
        run: go fmt ./...

      - name: Report likely mistakes
        run: go vet ./...

      - name: Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./...

      # - name: Test
      #   run: go test -v -race -cover -coverprofile=coverage ./...

      - name: Build
        run: CGO_ENABLED=0 go build -buildmode pie -buildvcs=false -ldflags "-s -w -extldflags '-static'" -trimpath
